# Generated by Django 2.0.4 on 2018-07-05 14:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UseerProfileInfo',
            new_name='UserProfileInfo',
        ),
    ]
